"""Run `python -m aml --help` for generation, training and scoring."""

import argparse
import json
from pathlib import Path
import joblib
import pandas as pd
import sklearn
from .data import generate_transactions
from .features import FEATURES
from .model import run_experiment, score_transactions
from .plots import pr_figure


def read_transactions(source):
    return pd.read_csv(source, dtype={"transaction_id": str, "sender": str, "receiver": str})


def write_experiment(experiment, output):
    output = Path(output)
    output.mkdir(parents=True, exist_ok=True)
    tx, report = experiment.transactions, experiment.report
    tx.query("split == 'test'").to_csv(output / "test_scores.csv", index=False)
    (output / "metrics.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    importance = pd.DataFrame({"feature": FEATURES, "importance": experiment.model.feature_importances_})
    importance.sort_values("importance", ascending=False).to_csv(output / "feature_importance.csv", index=False)
    joblib.dump({"model": experiment.model, "threshold": experiment.threshold,
                 "features": FEATURES, "sklearn_version": sklearn.__version__}, output / "model.joblib")
    if experiment.gnn is not None:
        from .gnn import save_graphsage
        from .plots import gnn_network_figure
        save_graphsage(experiment.gnn, output / "graphsage.pt")
        pd.DataFrame(report["gnn"]["training_history"]).to_csv(output / "gnn_training.csv", index=False)
        pd.DataFrame(experiment.graph_edges.T, columns=["source_index", "target_index"]).to_csv(output / "graph_edges.csv", index=False)
        selected = tx.query("split == 'test'").sort_values("gnn_score", ascending=False).iloc[0].transaction_id
        network, _ = gnn_network_figure(tx, experiment.graph_edges, selected)
        network.update_layout(paper_bgcolor="#0d1724", plot_bgcolor="#0d1724",
                              title="GraphSAGE context: transaction nodes, past-to-later messages")
        network.write_html(output / "gnn_network.html", include_plotlyjs=True)
    chart = pr_figure(experiment)
    chart.update_layout(paper_bgcolor="#0d1724", plot_bgcolor="#0d1724")
    chart.write_html(output / "precision_recall.html", include_plotlyjs=True)
    lines = ["# Synthetic AML evaluation", "", f"Generated by AML Investigator. Random seed: {report['seed']}.", "",
             "Results describe this synthetic generator only; they do not estimate real banking performance.", "",
             "| Model | Average precision | Precision | Recall | Alert rate | False positives / 1,000 |",
             "|---|---:|---:|---:|---:|---:|"]
    for name, m in report["test"].items():
        lines.append(f"| {name} | {m['average_precision']:.3f} | {m['precision']:.1%} | {m['recall']:.1%} | {m['alert_rate']:.1%} | {m['false_positives_per_1000']:.1f} |")
    lines.extend(["", "## Evaluation protocol", "",
        "Calendar days are split 60% / 20% / 20% into training, validation and test. Features use only earlier timestamps. "
        f"The alert threshold is set using validation scores to stay within a {report['validation_alert_budget']:.1%} alert budget; the test alert rate may differ. "
        "Rule-score ties can make their threshold more conservative. Ranking precision at the budget is also included in metrics.json.", "",
        "## Recall by injected pattern", ""])
    for name, stats in report.get("recall_by_pattern", {}).items():
        lines.append(f"- {name}: {stats['recall']:.1%} ({stats['transactions']} positive transactions).")
    if experiment.gnn is not None:
        lines.extend(["", "## GraphSAGE", "",
            f"Two layers of mean message passing over {report['gnn']['graph_nodes']:,} transaction nodes and "
            f"{report['gnn']['graph_edges']:,} directed temporal edges. "
            f"Validation selected epoch {report['gnn']['best_epoch']} out of {report['gnn']['epochs_run']} epochs run.", "",
            "Messages arrive only from earlier transactions sharing an account (at most eight neighbours within 24 hours per edge). "
            "The optimisation graph contains training nodes only. Normalisation is fitted on training features. "
            "Checkpoint selection and alert threshold use validation data; the held-out test is evaluated afterwards.", "",
            f"| Detector | Precision at the top {report['validation_alert_budget']:.1%} ranking budget |", "|---|---:|"])
        for name, stats in report["test"].items():
            lines.append(f"| {name} | {stats['precision_at_budget']:.1%} |")
        lines.extend(["", "GNN recall by injected pattern:", ""])
        for name, stats in report.get("gnn_recall_by_pattern", {}).items():
            lines.append(f"- {name}: {stats['recall']:.1%} ({stats['transactions']} positive transactions).")
    lines.extend(["", "First transfers of a pattern often have little historical evidence. Legitimate lookalikes are deliberately included. "
                  "Rule evidence is contextual information, not a causal explanation of the random forest.", ""])
    (output / "REPORT.md").write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="AML Investigator — synthetic transaction monitoring")
    commands = parser.add_subparsers(dest="command", required=True)
    for name in ("demo", "generate"):
        command = commands.add_parser(name)
        command.add_argument("--seed", type=int, default=42)
        command.add_argument("--days", type=int, default=90)
        command.add_argument("--accounts", type=int, default=500)
        command.add_argument("--daily-transactions", type=int, default=250)
        command.add_argument("--output", default="artifacts" if name == "demo" else "transactions.csv")
        if name == "demo":
            command.add_argument("--budget", type=float, default=0.05)
            command.add_argument("--gnn", action="store_true", help="Train temporal GraphSAGE alongside the baselines")
            command.add_argument("--gnn-epochs", type=int, default=40)
    train = commands.add_parser("train")
    train.add_argument("--input", required=True)
    train.add_argument("--output", default="artifacts")
    train.add_argument("--seed", type=int, default=42)
    train.add_argument("--budget", type=float, default=0.05)
    train.add_argument("--gnn", action="store_true")
    train.add_argument("--gnn-epochs", type=int, default=40)
    score = commands.add_parser("score")
    score.add_argument("--input", required=True)
    score.add_argument("--history", help="Earlier transactions to initialise the 24h feature history")
    score.add_argument("--model", default="artifacts/model.joblib", help="Trusted locally trained model only")
    score.add_argument("--gnn-model", help="Also score with a saved GraphSAGE checkpoint")
    score.add_argument("--output", default="scores.csv")
    args = parser.parse_args()
    try:
        if args.command in ("generate", "demo"):
            data = generate_transactions(args.seed, args.days, args.accounts, args.daily_transactions)
            if args.command == "generate":
                Path(args.output).parent.mkdir(parents=True, exist_ok=True)
                data.to_csv(args.output, index=False)
                print(f"Saved {len(data):,} synthetic transactions to {args.output}")
                return
        elif args.command == "train":
            data = read_transactions(args.input)
        else:
            bundle = joblib.load(args.model)
            if bundle.get("sklearn_version") != sklearn.__version__ or bundle.get("features") != FEATURES:
                raise ValueError("Model version/schema differs. Retrain with this environment.")
            history = read_transactions(args.history) if args.history else None
            scores = score_transactions(bundle["model"], read_transactions(args.input), bundle["threshold"], history)
            if args.gnn_model:
                from .gnn import load_graphsage, score_graphsage
                gnn_scores = score_graphsage(load_graphsage(args.gnn_model), read_transactions(args.input), history)
                scores = scores.merge(gnn_scores[["transaction_id", "gnn_score", "gnn_alert"]], on="transaction_id", validate="one_to_one")
            Path(args.output).parent.mkdir(parents=True, exist_ok=True)
            scores.to_csv(args.output, index=False)
            print(f"Scored {len(scores):,} transactions; {int(scores.alert.sum()):,} alerts. Saved {args.output}")
            return
        experiment = run_experiment(data, args.seed, args.budget, with_gnn=args.gnn, gnn_epochs=args.gnn_epochs)
        write_experiment(experiment, args.output)
        if args.command == "demo":
            data.to_csv(Path(args.output) / "transactions.csv", index=False)
        print(json.dumps(experiment.report["test"], indent=2))
        print(f"Saved reproducible results to {args.output}")
    except (ValueError, OSError, KeyError) as error:
        parser.exit(2, f"Error: {error}\n")


if __name__ == "__main__":
    main()
