[theme]
base = "dark"
primaryColor = "#4de0c1"
backgroundColor = "#0d1724"
secondaryBackgroundColor = "#152333"
textColor = "#dce5f0"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"
maxUploadSize = 20
